### ISSUE TITLE
Please set a license

### ISSUE THREAD

**Issue by kleag** [sriniiyer/concode#1]
Hi,
Thanks for sharing your code. Could you please associate a license to it? Without any license, nobody has the right to reuse your code, even for other research.
If you don't know which license to chose, I would suggest MIT which gives the most liberty to people or GPL which ensures the copies of your code will stay free.
Best regards,

**Comment by sriniiyer** [comment]
Done

**Comment by kleag** [comment]
Thanks a lot!
